id = "Blade Runner 2049"
name = "Blade Runner 2049 Theme"
authors = ["David C Cavalcante <davcavalcante@proton.me>", "Takk™ Innovate Studio <say@takk.ag>"]
version = "1.0.0"
schema_version = 1
description = "📺 A cyberpunk aesthetic theme based on the command line interface of Blade Runner 2049, inspired by the film's dystopian and high-tech visual style"
repository = "https://github.com/takk8is/blade-runner-2049-theme-for-zed"
